class Model {
  static List<String> car_name = [
    'BMW 7 Series',
    'Fortuner Leg.',
    'XUV700',
    'Mercedes-Benz',
    'Range Rover',
    'Discovery',
    'Rolls Royce',
    'Tesla',
    'Volvo',
    'Audi',
    'Porsche',
    'Lexus',
    'Ferrari',
    'Jeguar',
    'Bugatti',
    'Aston Martin',
  ];

  static List<String> car_images = [
    'images/bmw.png',
    'images/fortuner.png',
    'images/xuv700.png',
    'images/benz.png',
    'images/RR.png',
    'images/discovery.png',
    'images/roll_royce.png',
    'images/tesla.png',
    'images/volvo.png',
    'images/audi.png',
    'images/porsche.png',
    'images/lexus.png',
    'images/ferrari.png',
    'images/jeguar.png',
    'images/buggati.png',
    'images/aston_martin.png',
  ];

  static List<String> car_price = [
    '\$ 106,800',
    '\$ 93,500',
    '\$ 79,800',
    '\$ 102,100',
    '\$ 157,600',
    '\$ 110,300',
    '\$ 650,000',
    '\$ 540,000',
    '\$ 230,000',
    '\$ 104,000',
    '\$ 467,000',
    '\$ 234,000',
    '\$ 674,000',
    '\$ 397,000',
    '\$ 1,965,000',
    '\$ 436,000',
  ];

  static List<String> car_description = [
    '○ ARAI Mileage  :  39.53 kmpl\n○ Engine Displacement (cc)  :  2998\n○ Seating Capacity  :  4\n○ Fuel Tank Capacity  :  46.0\n○ Fuel Type  :  Petrol\n○ TransmissionType  :  Automatic',
    '○ ARAI Mileage  :  10.52 kmpl\n○ Engine Displacement (cc)  :  2755\n○ Seating Capacity  :  7\n○ Fuel Tank Capacity  :  80.0\n○ Fuel Type  :  Diesel\n○ TransmissionType  :  Automatic',
    '○ ARAI Mileage  :  17.19 kmpl\n○ Engine Displacement (cc)  :  2198\n○ Seating Capacity  :  7\n○ Fuel Tank Capacity  :  60.0\n○ Fuel Type  :  Diesel\n○ TransmissionType  :  Automatic',
    '○ ARAI Mileage  :  17.90 kmpl\n○ Engine Displacement (cc)  :  1991\n○ Seating Capacity  :  4\n○ Fuel Tank Capacity  :  66.0\n○ Fuel Type  :  Diesel\n○ TransmissionType  :  Automatic',
    '○ ARAI Mileage  :  39.53 kmpl\n○ Engine Displacement (cc)  :  2998\n○ Seating Capacity  :  4\n○ Fuel Tank Capacity  :  46.0\n○ Fuel Type  :  Diesel\n○ TransmissionType  :  Automatic',
    '○ ARAI Mileage  :  10.52 kmpl\n○ Engine Displacement (cc)  :  2755\n○ Seating Capacity  :  7\n○ Fuel Tank Capacity  :  80.0\n○ Fuel Type  :  Diesel\n○ TransmissionType  :  Automatic',
    '○ ARAI Mileage  :  17.19 kmpl\n○ Engine Displacement (cc)  :  2198\n○ Seating Capacity  :  4\n○ Fuel Tank Capacity  :  60.0\n○ Fuel Type  :  Diesel\n○ TransmissionType  :  Automatic',
    '○ ARAI Mileage  :  17.90 kmpl\n○ Engine Displacement (cc)  :  1991\n○ Seating Capacity  :  4\n○ Fuel Tank Capacity  :  66.0\n○ Fuel Type  :  Diesel\n○ TransmissionType  :  Automatic',
    '○ ARAI Mileage  :  39.53 kmpl\n○ Engine Displacement (cc)  :  2998\n○ Seating Capacity  :  4\n○ Fuel Tank Capacity  :  46.0\n○ Fuel Type  :  Diesel\n○ TransmissionType  :  Automatic',
    '○ ARAI Mileage  :  10.52 kmpl\n○ Engine Displacement (cc)  :  2755\n○ Seating Capacity  :  4\n○ Fuel Tank Capacity  :  80.0\n○ Fuel Type  :  Diesel\n○ TransmissionType  :  Automatic',
    '○ ARAI Mileage  :  17.19 kmpl\n○ Engine Displacement (cc)  :  2198\n○ Seating Capacity  :  4\n○ Fuel Tank Capacity  :  60.0\n○ Fuel Type  :  Diesel\n○ TransmissionType  :  Automatic',
    '○ ARAI Mileage  :  17.90 kmpl\n○ Engine Displacement (cc)  :  1991\n○ Seating Capacity  :  4\n○ Fuel Tank Capacity  :  66.0\n○ Fuel Type  :  Diesel\n○ TransmissionType  :  Automatic',
    '○ ARAI Mileage  :  39.53 kmpl\n○ Engine Displacement (cc)  :  2998\n○ Seating Capacity  :  4\n○ Fuel Tank Capacity  :  46.0\n○ Fuel Type  :  Diesel\n○ TransmissionType  :  Automatic',
    '○ ARAI Mileage  :  10.52 kmpl\n○ Engine Displacement (cc)  :  2755\n○ Seating Capacity  :  4\n○ Fuel Tank Capacity  :  80.0\n○ Fuel Type  :  Petrol\n○ TransmissionType  :  Automatic',
    '○ ARAI Mileage  :  17.19 kmpl\n○ Engine Displacement (cc)  :  2198\n○ Seating Capacity  :  4\n○ Fuel Tank Capacity  :  60.0\n○ Fuel Type  :  Diesel\n○ TransmissionType  :  Automatic',
    '○ ARAI Mileage  :  17.90 kmpl\n○ Engine Displacement (cc)  :  1991\n○ Seating Capacity  :  4\n○ Fuel Tank Capacity  :  66.0\n○ Fuel Type  :  Petrol\n○ TransmissionType  :  Automatic',
  ];
}
